/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model.impl;

import com.datamusic.app.model.CollectionItem;
import com.datamusic.app.service.CollectionItemLocalServiceUtil;

/**
 * The extended model base implementation for the CollectionItem service. Represents a row in the &quot;datamusic_CollectionItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CollectionItemImpl}.
 * </p>
 *
 * @author Regisson Aguiar
 * @see CollectionItemImpl
 * @see CollectionItem
 * @generated
 */
public abstract class CollectionItemBaseImpl
	extends CollectionItemModelImpl implements CollectionItem {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a collection item model instance should use the <code>CollectionItem</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CollectionItemLocalServiceUtil.addCollectionItem(this);
		}
		else {
			CollectionItemLocalServiceUtil.updateCollectionItem(this);
		}
	}

}