/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model.impl;

import com.datamusic.app.model.Media;
import com.datamusic.app.service.MediaLocalServiceUtil;

/**
 * The extended model base implementation for the Media service. Represents a row in the &quot;datamusic_Media&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MediaImpl}.
 * </p>
 *
 * @author Regisson Aguiar
 * @see MediaImpl
 * @see Media
 * @generated
 */
public abstract class MediaBaseImpl extends MediaModelImpl implements Media {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a media model instance should use the <code>Media</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MediaLocalServiceUtil.addMedia(this);
		}
		else {
			MediaLocalServiceUtil.updateMedia(this);
		}
	}

}