/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model.impl;

import com.datamusic.app.model.UserAccount;
import com.datamusic.app.service.UserAccountLocalServiceUtil;

/**
 * The extended model base implementation for the UserAccount service. Represents a row in the &quot;datamusic_UserAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserAccountImpl}.
 * </p>
 *
 * @author Regisson Aguiar
 * @see UserAccountImpl
 * @see UserAccount
 * @generated
 */
public abstract class UserAccountBaseImpl
	extends UserAccountModelImpl implements UserAccount {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user account model instance should use the <code>UserAccount</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserAccountLocalServiceUtil.addUserAccount(this);
		}
		else {
			UserAccountLocalServiceUtil.updateUserAccount(this);
		}
	}

}