/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CollectionItem service. Represents a row in the &quot;datamusic_CollectionItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.datamusic.app.model.impl.CollectionItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.datamusic.app.model.impl.CollectionItemImpl</code>.
 * </p>
 *
 * @author Regisson Aguiar
 * @see CollectionItem
 * @generated
 */
@ProviderType
public interface CollectionItemModel
	extends BaseModel<CollectionItem>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a collection item model instance should use the {@link CollectionItem} interface instead.
	 */

	/**
	 * Returns the primary key of this collection item.
	 *
	 * @return the primary key of this collection item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this collection item.
	 *
	 * @param primaryKey the primary key of this collection item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this collection item.
	 *
	 * @return the mvcc version of this collection item
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this collection item.
	 *
	 * @param mvccVersion the mvcc version of this collection item
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this collection item.
	 *
	 * @return the uuid of this collection item
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this collection item.
	 *
	 * @param uuid the uuid of this collection item
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the collection item ID of this collection item.
	 *
	 * @return the collection item ID of this collection item
	 */
	public long getCollectionItemId();

	/**
	 * Sets the collection item ID of this collection item.
	 *
	 * @param collectionItemId the collection item ID of this collection item
	 */
	public void setCollectionItemId(long collectionItemId);

	/**
	 * Returns the company ID of this collection item.
	 *
	 * @return the company ID of this collection item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this collection item.
	 *
	 * @param companyId the company ID of this collection item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this collection item.
	 *
	 * @return the create date of this collection item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this collection item.
	 *
	 * @param createDate the create date of this collection item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this collection item.
	 *
	 * @return the modified date of this collection item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this collection item.
	 *
	 * @param modifiedDate the modified date of this collection item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user account ID of this collection item.
	 *
	 * @return the user account ID of this collection item
	 */
	public long getUserAccountId();

	/**
	 * Sets the user account ID of this collection item.
	 *
	 * @param userAccountId the user account ID of this collection item
	 */
	public void setUserAccountId(long userAccountId);

	/**
	 * Returns the media ID of this collection item.
	 *
	 * @return the media ID of this collection item
	 */
	public long getMediaId();

	/**
	 * Sets the media ID of this collection item.
	 *
	 * @param mediaId the media ID of this collection item
	 */
	public void setMediaId(long mediaId);

	/**
	 * Returns the review of this collection item.
	 *
	 * @return the review of this collection item
	 */
	@AutoEscape
	public String getReview();

	/**
	 * Sets the review of this collection item.
	 *
	 * @param review the review of this collection item
	 */
	public void setReview(String review);

	/**
	 * Returns the rating of this collection item.
	 *
	 * @return the rating of this collection item
	 */
	public int getRating();

	/**
	 * Sets the rating of this collection item.
	 *
	 * @param rating the rating of this collection item
	 */
	public void setRating(int rating);

	@Override
	public CollectionItem cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}