/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Media service. Represents a row in the &quot;datamusic_Media&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.datamusic.app.model.impl.MediaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.datamusic.app.model.impl.MediaImpl</code>.
 * </p>
 *
 * @author Regisson Aguiar
 * @see Media
 * @generated
 */
@ProviderType
public interface MediaModel
	extends BaseModel<Media>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a media model instance should use the {@link Media} interface instead.
	 */

	/**
	 * Returns the primary key of this media.
	 *
	 * @return the primary key of this media
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this media.
	 *
	 * @param primaryKey the primary key of this media
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this media.
	 *
	 * @return the mvcc version of this media
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this media.
	 *
	 * @param mvccVersion the mvcc version of this media
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this media.
	 *
	 * @return the uuid of this media
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this media.
	 *
	 * @param uuid the uuid of this media
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the media ID of this media.
	 *
	 * @return the media ID of this media
	 */
	public long getMediaId();

	/**
	 * Sets the media ID of this media.
	 *
	 * @param mediaId the media ID of this media
	 */
	public void setMediaId(long mediaId);

	/**
	 * Returns the company ID of this media.
	 *
	 * @return the company ID of this media
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this media.
	 *
	 * @param companyId the company ID of this media
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this media.
	 *
	 * @return the create date of this media
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this media.
	 *
	 * @param createDate the create date of this media
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this media.
	 *
	 * @return the modified date of this media
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this media.
	 *
	 * @param modifiedDate the modified date of this media
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the media name of this media.
	 *
	 * @return the media name of this media
	 */
	@AutoEscape
	public String getMediaName();

	/**
	 * Sets the media name of this media.
	 *
	 * @param mediaName the media name of this media
	 */
	public void setMediaName(String mediaName);

	/**
	 * Returns the artist of this media.
	 *
	 * @return the artist of this media
	 */
	@AutoEscape
	public String getArtist();

	/**
	 * Sets the artist of this media.
	 *
	 * @param artist the artist of this media
	 */
	public void setArtist(String artist);

	/**
	 * Returns the description of this media.
	 *
	 * @return the description of this media
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this media.
	 *
	 * @param description the description of this media
	 */
	public void setDescription(String description);

	/**
	 * Returns the genre of this media.
	 *
	 * @return the genre of this media
	 */
	@AutoEscape
	public String getGenre();

	/**
	 * Sets the genre of this media.
	 *
	 * @param genre the genre of this media
	 */
	public void setGenre(String genre);

	@Override
	public Media cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}