/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.datamusic.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserAccount service. Represents a row in the &quot;datamusic_UserAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.datamusic.app.model.impl.UserAccountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.datamusic.app.model.impl.UserAccountImpl</code>.
 * </p>
 *
 * @author Regisson Aguiar
 * @see UserAccount
 * @generated
 */
@ProviderType
public interface UserAccountModel
	extends BaseModel<UserAccount>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user account model instance should use the {@link UserAccount} interface instead.
	 */

	/**
	 * Returns the primary key of this user account.
	 *
	 * @return the primary key of this user account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user account.
	 *
	 * @param primaryKey the primary key of this user account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this user account.
	 *
	 * @return the mvcc version of this user account
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this user account.
	 *
	 * @param mvccVersion the mvcc version of this user account
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this user account.
	 *
	 * @return the uuid of this user account
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user account.
	 *
	 * @param uuid the uuid of this user account
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user account ID of this user account.
	 *
	 * @return the user account ID of this user account
	 */
	public long getUserAccountId();

	/**
	 * Sets the user account ID of this user account.
	 *
	 * @param userAccountId the user account ID of this user account
	 */
	public void setUserAccountId(long userAccountId);

	/**
	 * Returns the company ID of this user account.
	 *
	 * @return the company ID of this user account
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user account.
	 *
	 * @param companyId the company ID of this user account
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this user account.
	 *
	 * @return the create date of this user account
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user account.
	 *
	 * @param createDate the create date of this user account
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user account.
	 *
	 * @return the modified date of this user account
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user account.
	 *
	 * @param modifiedDate the modified date of this user account
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user name account of this user account.
	 *
	 * @return the user name account of this user account
	 */
	@AutoEscape
	public String getUserNameAccount();

	/**
	 * Sets the user name account of this user account.
	 *
	 * @param userNameAccount the user name account of this user account
	 */
	public void setUserNameAccount(String userNameAccount);

	/**
	 * Returns the user first name of this user account.
	 *
	 * @return the user first name of this user account
	 */
	@AutoEscape
	public String getUserFirstName();

	/**
	 * Sets the user first name of this user account.
	 *
	 * @param userFirstName the user first name of this user account
	 */
	public void setUserFirstName(String userFirstName);

	/**
	 * Returns the user last name of this user account.
	 *
	 * @return the user last name of this user account
	 */
	@AutoEscape
	public String getUserLastName();

	/**
	 * Sets the user last name of this user account.
	 *
	 * @param userLastName the user last name of this user account
	 */
	public void setUserLastName(String userLastName);

	@Override
	public UserAccount cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}